// TODOS
export const GET_TODOS = "GET_TODOS";
export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const TODOS_LOADING = "TODOS_LOADING";

//SIDEBAR
export const GET_SIDEBAR_ACTIVE = "GET_SIDEBAR_ACTIVE";
export const TOOGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// PROJECTS
export const SET_PROJECT_MODAL_STATE = "SET_PROJECT_MODAL_STATE";
export const UPDATE_MODAL_INPUT = "UPDATE_MODAL_INPUT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
export const SET_PROJECT_COLOR = "SET_PROJECT_COLOR";

// Activites
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const SET_ACTIVITY_MODAL_STATE = "SET_ACTIVITY_MODAL_STATE";
export const UPDATE_ACTIVITY_MODAL_INPUT = "UPDATE_ACTIVITY_MODAL_INPUT";
export const SET_TEMP_START = "SET_TEMP_START";
export const SET_TEMP_END = "SET_TEMP_END";
export const SET_ACTIVITY_TRACK_MODAL_STATE = "SET_ACTIVITY_TRACK_MODAL_STATE";
export const SET_ACTIVE_DATE = "SET_ACTIVE_DATE";
export const SET_SELECTED_TRACK = "SET_SELECTED_TRACK";

// Tracks
export const GET_TRACKS = "GET_TRACKS";
export const ADD_TRACK = "ADD_TRACK";
export const DELETE_TRACK = "DELETE_TRACK";
export const UPDATE_TRACK = "UPDATE_TRACK";
export const SET_ACTIVE_ACTIVITY = "SET_ACTIVE_ACTIVITY";
export const SET_ACTIVITY_DURATION = "SET_ACTIVITY_DURATION";
export const SET_ACTIVE_ACTIVITY_START = "SET_ACTIVE_ACTIVITY_START";
